# Generated by Django 5.0.1 on 2024-01-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField()),
                ('medical_history', models.TextField()),
                ('visit_notes', models.TextField()),
                ('operations', models.TextField()),
                ('vaccinations', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('prescribed_date', models.DateField()),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_record.patientrecord')),
            ],
        ),
    ]
