# Generated by Django 5.0.1 on 2024-01-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0002_calendar_doctor_reservation_patient'),
        ('worker', '0004_doctor_is_worker_secretary_is_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.doctor'),
        ),
    ]
