# Generated by Django 5.0.1 on 2024-01-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prof_title',
            field=models.CharField(choices=[('MD', 'Doktor medycyny'), ('PhD', 'Doktor nauk medycznych'), ('Prof.', 'Profesor'), ('Dr hab. med.', 'Doktor habilitowany medycyny'), ('Spec.', 'Specjalista'), ('Asystent', 'Młodszy lekarz'), ('Doc.', 'Docent'), ('Doc. hab.', 'Doktor habilitowany'), ('Doc. dr', 'Doktor habilitowany nauk medycznych'), ('Dr. med.', 'Doktor medycyny'), ('Kier. lab.', 'Kierownik laboratorium'), ('Prof. dr hab. med.', 'Profesor doktor habilitowany medycyny'), ('Doc. dr hab. med.', 'Docent doktor habilitowany medycyny'), ('Dr n. med.', 'Doktor nauk medycznych'), ('Dr inż.', 'Doktor inżynier'), ('Dr med. vet.', 'Doktor medycyny weterynaryjnej'), ('Dr dent.', 'Doktor stomatologii')], default='Dr. med.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='employment_status',
            field=models.CharField(choices=[('aktywny', 'Aktywny'), ('na_urlopie', 'Na Urlopie'), ('nieaktywny', 'Nieaktywny')], default='Aktywny'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='employment_status',
            field=models.CharField(choices=[('aktywny', 'Aktywny'), ('na_urlopie', 'Na Urlopie'), ('nieaktywny', 'Nieaktywny')], default='Aktywny'),
        ),
    ]
