# Generated by Django 5.0.1 on 2024-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_doctor_prof_title_alter_doctor_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_worker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secretary',
            name='is_worker',
            field=models.BooleanField(default=True),
        ),
    ]
