# Generated by Django 5.0.1 on 2024-01-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('secretary', 'Secretary'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
